-- Thanks to http://icon.shef.ac.uk/Moby/mpos.html for Grady Ward's Moby's parts of speech

DROP TABLE PART_OF_SPEECH;
DROP TABLE SPEECH_CATEGORIES;
DROP TABLE DICTIONARY;

-- Table creation

CREATE TABLE DICTIONARY(
	WORD_ID 	 INTEGER PRIMARY KEY,	
    WORD         VARCHAR(255) NOT NULL
    
);

CREATE TABLE SPEECH_CATEGORIES(
	DESCRIPTION  VARCHAR(21) NOT NULL, 
	SPEECH_PART  VARCHAR(1)  NOT NULL PRIMARY KEY
);

CREATE TABLE PART_OF_SPEECH(
	WORD_ID      INTEGER NOT NULL,
	SPEECH_PART  VARCHAR(1)  NOT NULL 
);


--Constraints

ALTER TABLE PART_OF_SPEECH
	ADD CONSTRAINT "FK_WORD_ID"     FOREIGN KEY (WORD_ID)     REFERENCES DICTIONARY, 
	ADD CONSTRAINT "FK_SPEECH_PART" FOREIGN KEY (SPEECH_PART) REFERENCES SPEECH_CATEGORIES, 
	ADD CONSTRAINT "PK_SPEECH"      PRIMARY KEY (WORD_ID,SPEECH_PART)
;

-- SPEECH_CATEGORIES poblate
	
INSERT INTO SPEECH_CATEGORIES VALUES ('Noun','N');
INSERT INTO SPEECH_CATEGORIES VALUES ('Plural','p');
INSERT INTO SPEECH_CATEGORIES VALUES ('Noun Phrase','h');
INSERT INTO SPEECH_CATEGORIES VALUES ('Verb (usu participle)','V');
INSERT INTO SPEECH_CATEGORIES VALUES ('Verb (transitive)','t');
INSERT INTO SPEECH_CATEGORIES VALUES ('Verb (intransitive)','i');
INSERT INTO SPEECH_CATEGORIES VALUES ('Adjective','A');
INSERT INTO SPEECH_CATEGORIES VALUES ('Adverb','v');
INSERT INTO SPEECH_CATEGORIES VALUES ('Conjunction','C');
INSERT INTO SPEECH_CATEGORIES VALUES ('Preposition','P');
INSERT INTO SPEECH_CATEGORIES VALUES ('Interjection','!');
INSERT INTO SPEECH_CATEGORIES VALUES ('Pronoun','r');
INSERT INTO SPEECH_CATEGORIES VALUES ('Definite Article','D');
INSERT INTO SPEECH_CATEGORIES VALUES ('Indefinite Article','I');
INSERT INTO SPEECH_CATEGORIES VALUES ('Nominative','o');

-- Count of elements for each part of the speech

CREATE OR REPLACE VIEW speech_count 
AS
SELECT sc.description, sc.speech_part, COUNT(*)
	FROM PART_OF_SPEECH p, SPEECH_CATEGORIES sc
		WHERE p.speech_part = sc.speech_part
			GROUP BY sc.description, sc.speech_part, p.speech_part;